<a href="https://colab.research.google.com/github/RafsanJany-44/Thesis_Project/blob/main/MEGA_SVM_10f.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Load, Split dataset and Scaling** 

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# load dataset
dataset = pd.read_csv('/content/drive/MyDrive/Thesis_Data/MEGA_10f.csv')

# Split Dataset into X and Y
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

# Split the X and Y Dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Perform Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Fit SVM to the Training set**

In [3]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [4]:
#Predict the Test Set Results
y_pred = classifier.predict(X_test)

**Make the Confusion Matrix**

In [5]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[  23 1227   65  620 1034]
 [  15 7726  813  582  679]
 [   2 2980 2054  142  114]
 [   7 1781  149 1899  385]
 [  19  883  247  400 3267]]


In [6]:
accuracy_score(y_test,y_pred)

0.5520967801423672