<a href="https://colab.research.google.com/github/RafsanJany-44/Thesis_Project/blob/main/MEGA_SVM_20f.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Load, Split dataset and Scaling** 

In [23]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# load dataset
dataset = pd.read_csv('/content/drive/MyDrive/Thesis_Data/MEGA_20f.csv')

# Split Dataset into X and Y
X = dataset.iloc[:, 1:16].values
y = dataset.iloc[:, 0].values

# Split the X and Y Dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Perform Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Fit SVM to the Training set**

In [25]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [26]:
#Predict the Test Set Results
y_pred = classifier.predict(X_test)

**Make the Confusion Matrix**

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 219  979   59  626 1086]
 [  85 7729  921  604  476]
 [   3 2175 2958   97   59]
 [  90 1639  116 2168  208]
 [ 126  388  105  237 3960]]


In [28]:
accuracy_score(y_test,y_pred)

0.6282595065097923