<a href="https://colab.research.google.com/github/RafsanJany-44/Thesis_Project/blob/main/SKLearn_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

In [6]:
data = 'https://raw.githubusercontent.com/RafsanJany-44/Thesis_Project/main/All_DATA/without_sn_and_Epoch/EEG_HMC_NUM.csv'

dataset = pd.read_csv(data)

In [7]:
X = dataset.iloc[:, 1:76].values
y = dataset.iloc[:, 0].values

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 0)

In [9]:
X_train.shape, X_test.shape

((72662, 75), (35789, 75))

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train =sc.fit_transform(X_train)

X_test =sc.fit_transform(X_test)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
KNN_class = KNeighborsClassifier(n_neighbors=3)
KNN_class.fit(X, y)
y_pred=KNN_class.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[   1    0 2191 4199    0]
 [   0    0 1357 2550    0]
 [   0    0 7317 5654    0]
 [   0    0 5051 1956    0]
 [   0    0 2061 3452    0]]
              precision    recall  f1-score   support

           0       1.00      0.00      0.00      6391
           1       0.00      0.00      0.00      3907
           2       0.41      0.56      0.47     12971
           3       0.11      0.28      0.16      7007
           4       0.00      0.00      0.00      5513

    accuracy                           0.26     35789
   macro avg       0.30      0.17      0.13     35789
weighted avg       0.35      0.26      0.20     35789

Accurecy:  0.25912990024867977


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
