**Load, Split dataset and Scaling** 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# load dataset
dataset = pd.read_csv('/content/drive/MyDrive/Thesis_Data/EEG_HMC_underscore.csv')

# Split Dataset into X and Y
X = dataset.iloc[:, 1:16].values
y = dataset.iloc[:, 0].values

# Split the X and Y Dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Perform Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Fit SVM to the Training set**

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [ ]:
#Predict the Test Set Results
y_pred = classifier.predict(X_test)

**Make the Confusion Matrix**

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 150  989   57  671 1102]
 [  51 7527  992  717  528]
 [   0 2180 2962   96   54]
 [  61 1428  146 2314  272]
 [ 128  429   69  266 3924]]


In [ ]:
accuracy_score(y_test,y_pred)

0.6224689263452956