<a href="https://colab.research.google.com/github/RafsanJany-44/Thesis_Project/blob/main/SKLearn_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np

In [14]:
data = 'https://raw.githubusercontent.com/RafsanJany-44/Thesis_Project/main/All_DATA/without_sn_and_Epoch/EEG_HMC_NUM.csv'

dataset = pd.read_csv(data)

In [15]:
X = dataset.iloc[:, 1:76].values
y = dataset.iloc[:, 0].values

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 0)

In [17]:
X_train.shape, X_test.shape

((72662, 75), (35789, 75))

In [18]:
from sklearn.neighbors import KNeighborsClassifier
KNN_class = KNeighborsClassifier(n_neighbors=3)
KNN_class.fit(X, y)
y_pred=KNN_class.predict(X_test)

In [19]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[ 5950   236   148    26    31]
 [  827  2298   512    30   240]
 [  495   426 11109   650   291]
 [  155    49   623  6165    15]
 [  211   228   307    21  4746]]
              precision    recall  f1-score   support

           0       0.78      0.93      0.85      6391
           1       0.71      0.59      0.64      3907
           2       0.87      0.86      0.87     12971
           3       0.89      0.88      0.89      7007
           4       0.89      0.86      0.88      5513

    accuracy                           0.85     35789
   macro avg       0.83      0.82      0.82     35789
weighted avg       0.85      0.85      0.84     35789

Accurecy:  0.8457347229595685
